#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        iif "lo" accept                               # loopback always allowed
        ct state established,related accept           # stateful: allow replies
        iif "wlan0" tcp dport 22 accept               # SSH from WLAN
        iif "eth0"  tcp dport 22 accept               # SSH from LAN (own extension §5.4)
        udp dport 67 accept                           # DHCP server
        udp dport 53 accept                           # DNS (UDP)
        tcp dport 53 accept                           # DNS (TCP)
        ip protocol icmp accept                       # ICMP / ping
        log prefix "Dropped packet: " flags all drop  # log + drop everything else
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }

    chain forward {
        type filter hook forward priority 0; policy drop;

        iif "wlan0" oif "eth0" accept                 # WLAN -> internet
        ct state established,related accept           # allow return traffic
    }
}

table ip nat {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
    }
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        oif "eth0" masquerade                         # NAT for all WLAN clients
    }
}
